apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
    - default: # 此处定义默认限制值
        cpu: 500m
      defaultRequest: # 此处定义默认请求值
        cpu: 500m
      max: # max 和 min 定义限制范围
        cpu: '1'
      min:
        cpu: 100m
      maxLimitRequestRatio:
        cpu: "10"
        memory: "10"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit
spec:
  limits:
    - default: # 此处定义默认限制值
        cpu: 500m
      defaultRequest: # 此处定义默认请求值
        cpu: 500m
      max: # max 和 min 定义限制范围
        cpu: '1'
      min:
        cpu: 100m
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
    - max:
        cpu: "800m"
        memory: "1Gi"
      min:
        cpu: "100m"
        memory: "99Mi"
      default:
        cpu: "700m"
        memory: "900Mi"
      defaultRequest:
        cpu: "110m"
        memory: "111Mi"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-pod
spec:
  limits:
    - max:
        cpu: "2"
        memory: "2Gi"
      type: Pod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limits
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: 2Gi
      min:
        storage: 1Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-memory-ratio-pod
spec:
  limits:
    - maxLimitRequestRatio:
        memory: 2
      type: Pod
