apiVersion: v1
kind: Pod
metadata:
  name: security-context-allow-privilege-escalation
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups:
      - 2000
      - 3000
    seccompProfile:
      type: Localhost
      localhostProfile: my-profiles/profile-allow.json
  volumes:
    - name: sec-ctx-vol
      emptyDir: {}
  containers:
    - name: sec-ctx-demo
      image: busybox:1.28
      command: [ "sh", "-c", "sleep 1h" ]
      volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
      securityContext:
        seLinuxOptions:
          level: "s0:c123,c456"
        capabilities:
          add: [ "NET_ADMIN", "SYS_TIME" ]
        runAsUser: 2000
        allowPrivilegeEscalation: false
