---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yages
    example: grpc-routing
  name: yages
spec:
  selector:
    matchLabels:
      app: yages
  replicas: 1
  template:
    metadata:
      labels:
        app: yages
    spec:
      containers:
        - name: grpcsrv
          image: quay.io/mhausenblas/yages:0.1.0
          ports:
            - containerPort: 9000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yages
    example: grpc-routing
  name: yages
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: yages
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: yages
  labels:
    example: grpc-routing
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "grpc-example.lvh.me"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: yages
          port: 9000
          weight: 1
---
#grpcurl -plaintext -authority=grpc-example.lvh.me 127.0.0.1:80 yages.Echo/Ping
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: yages-matches
  labels:
    example: grpc-routing
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "grpc-example.matches.lvh.me"
  rules:
    - matches:
        - method:
            method: ServerReflectionInfo
            service: grpc.reflection.v1alpha.ServerReflection
        - method:
            method: Ping
      backendRefs:
        - group: ""
          kind: Service
          name: yages
          port: 9000
          weight: 1
---
#grpcurl -plaintext -authority=grpc-example.matches.lvh.me 127.0.0.1:80 yages.Echo/Ping
#grpcurl -plaintext -authority=grpc-example.matches.lvh.me 127.0.0.1:80 yages.Echo/ServerReflectionInfo
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: yages-regular-expression
  labels:
    example: grpc-routing
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "grpc-example.regular.lvh.me"
  rules:
    - matches:
        - method:
            method: ServerReflectionInfo
            service: grpc.reflection.v1alpha.ServerReflection
        - method:
            method: "Pin.+"
            service: ".*.Echo"
            type: RegularExpression
      backendRefs:
        - group: ""
          kind: Service
          name: yages
          port: 9000
          weight: 1
---
#grpcurl -plaintext -authority=grpc-example.regular.lvh.me 127.0.0.1:80 yages.Echo/Ping
