apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
  - name: my-registry-key
kind: ServiceAccount
metadata:
  name: sa-image-pull-secrets-blazor
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-automount-blazor
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-secret-blazor
  namespace: default
secrets:
  - name: secret-blazor1
    namespace: default
    kind: Secret
    fieldPath: spec.template.spec.volumes[0].secret
  - name: secret-blazor2
    namespace: default
    kind: Secret
    fieldPath: spec.template.spec.volumes[0].secret
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-blazor
  namespace: default
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICJhdXRoIjogImMzUi4uLnpFMiIKICAgICAgICB9CiAgICB9Cn0=
type: kubernetes.io/dockerconfigjson
