name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Server/Dockerfile --tag blzaork8s-server:$(date +%s)
